version: 2
jobs:
  build:
    machine: true
    working_directory: ~/test_repo
    steps:
      - checkout
      - run:
         name: "pwd command"
         command: pwd
      - run:
         name: "ls command"
         command: "ls -ltr"
      - run:
         name: "install powershell"
         command: bash /home/circleci/project/test_repo/.circleci/install-power-shell.sh
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date

