version: 2
jobs:
  build:
    steps:
      - checkout
      -run:
         name: "install powershell"
         command: bash ./install-power-shell.sh
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date

